# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on: 
  push:
    tags: 
      - "v*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: build image
      working-directory: aliyun-ddns/
      run: | 
        tag=$(git describe --tags --always)
        docker login -u ${{ secrets.ALIYUN_USERNAME }} -p ${{ secrets.ALIYUN_PWD }} ${{ secrets.ALIYUN_REPO }}
        docker buildx create --use
        docker buildx build --push -t ${{ secrets.ALIYUN_DOCKER_REPO }}:${tag} -f Dockerfile --platform linux/arm64,linux/amd64 .
