# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: build image
      working-directory: aliyun-ddns
      run: docker build -t aliyun-ddns-image -f Dockerfile ./aliyun-ddns
    - name: login
      run: docker login -u ${{ secrets.ALIYUN_USERNAME }} -p ${{ secrets.ALIYUN_PWD }} ${{ secrets.ALIYUN_REPO }}
    - name: push
      run: docker push ${{ secrets.ALIYUN_REPO }}:${{ github.run_id }}
